name: Tests
on: push

jobs:
  # <---------------- TEST BASIC CONFIG ------------------>
  basic:
    name: Basic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start
        uses: ./
        with:
          google-cloud-project: ${{ secrets.TEST_PROJECT }}
          service-account-keyfile: ${{ secrets.TEST_SA }}
          team: google-dep-metrics
          service: action-app
          environment: test
          status: started
          result: pending
          version: v0.1.1

      - name: Fake deploy
        id: deploy
        run: echo "Deployed"

      - name: Finish
        uses: ./
        with:
          google-cloud-project: ${{ secrets.TEST_PROJECT }}
          service-account-keyfile: ${{ secrets.TEST_SA }}
          team: google-dep-metrics
          service: action-app
          environment: test
          status: finished
          result: ${{ steps.deploy.outcome }}
          version: v0.1.1

